`bundle exec rake` should be able to find frontend and backend assets
solidusio-contrib/solidus_paypal_commerce_platform pull request #157
Opened 2022-05-20 10:13 UTC by gsmendoza

## Dependencies

This depends on https://github.com/solidusio-contrib/solidus_paypal_commerce_platform/pull/156.

Expected behavior
-----------------

Given I have a local clone of the SolidusPaypalCommercePlatform repo
When I run `bundle exec rake` 
Then I expect the specs to run and pass

Actual behavior
---------------

`bundle exec rake` encounters the following error:

```
An error occurred in a `before(:suite)` hook.
Failure/Error: //= link spree/backend/all.js

Sprockets::FileNotFound:
  couldn't find file 'spree/backend/all.js'
  Checked in these paths: 
    /home/gsmendoza/repos/solidusio-contrib/solidus_paypal_commerce_platform/spec/dummy/app/assets/config
    /home/gsmendoza/repos/solidusio-contrib/solidus_paypal_commerce_platform/spec/dummy/app/assets/images
    /home/gsmendoza/repos/solidusio-contrib/solidus_paypal_commerce_platform/spec/dummy/app/assets/stylesheets
    /home/gsmendoza/repos/solidusio-contrib/solidus_paypal_commerce_platform/app/assets/javascripts
    /home/gsmendoza/repos/solidusio-contrib/solidus_paypal_commerce_platform/app/assets/stylesheets
```

Cause
-----

`bundle exec rake` calls the tasks and methods below in the given order:

* `SolidusDevSupport::RakeTasks.install` 
* `SolidusDevSupport::RakeTasks.install_test_app_task` 
* The `extension:test_app rake task` (this is automatically invoked while the
  tasks are being installed!!!)
* `Solidus::InstallGenerator#setup_assets `

The `setup_assets` method would only install the `all.*` frontend and backend
assets if either

* `Spree::Frontend` and `Spree::Backend` are loaded, or
* The Rails environment is test.

Currently, when we run `bundle exec rake`, neither condition is met:

* `Spree::Frontend` and `Spree::Backend` are NOT loaded.
* The Rails environment is development.

`bundle exec rake` in CI doesn't have this issue because its postgres and mysql
executors set the Rails environment to test.

`bundle exec rspec` also doesn't have this issue, since the `spec_helper.rb`
file sets the Rails environment to test before calling `system 'bin/rake
extension:test_app'`.

Solution
--------

Load the `Spree::Frontend` and `Spree::Backend` classes before calling
`SolidusDevSupport::RakeTasks.install`. Letting `bundle exec rake` change the
environment to test is not an option since that would affect other rake
tasks.

2022-05-22 15:44 UTC, aldesantis approved these changes

2022-05-24 10:04 UTC, waiting-for-dev commented
It seems there's the same problem in https://github.com/solidusio-contrib/solidus_gdpr

Thanks for looking into it!

> Letting bundle exec rake change the
environment to test is not an option since that would affect other rake
tasks.

I haven't looked into it in detail, but, isn't it possible to only set the test environment when the executed talk is the default?

2022-05-26 07:01 UTC, gsmendoza commented
> I haven't looked into it in detail, but, isn't it possible to only set the test environment when the executed talk is the default?

Hmmm.. I think it should be possible to update the extension so that only `bundle exec rake` would run in a test environment. I suppose the task would work in the same way that the `db:test:prepare` rake task only affects the test database.

That being said, I prefer the current solution of requiring the backend and frontend libraries because scope of this solution is narrower than setting the environment to test. Setting the environment to test may result in unexpected side-effects in the future.

2022-06-02 06:12 UTC, gsmendoza commented on Rakefile
> +require 'spree/frontend'
@kennyadsl As far as I know, `Rakefile` is only used for developing SolidusPaypalCommercePlatform. When a store has SolidusPaypalCommercePlatform, it shouldn't load this file.

2022-06-02 10:07 UTC, aldesantis approved these changes

2022-06-02 11:23 UTC, waiting-for-dev requested changes
Hey, @gsmendoza!

Thanks for working on it!

I'd like to understand what's going on, as I think it's a bit confusing.

As I pointed out in the comment, and unless I'm wrong, the `Rakefile` here is just copied from the [template in `solidus_dev_support`](https://github.com/solidusio/solidus_dev_support/blob/master/lib/solidus_dev_support/templates/extension/Rakefile). That means that the place where we should probably fix the issue is there. Having `solidus_gdpr` affected by the same issue indeed points in that direction.

Your comment says that the issue can also be fixed by setting `RAILS_ENV` to `test` during the task execution. If that's the case, and given that `extensions:spec` is the [default task](https://github.com/solidusio-contrib/solidus_paypal_commerce_platform/blob/f3ed9d2423c4ad9f55b930258587d5f4a945301b/Rakefile#L6) run when doing `bin/rake`, we should be able to fix it by setting the environment variable in the [task definition in solidus_dev_support](https://github.com/solidusio/solidus_dev_support/blob/10335535efae144630d2a5783819adae8013843d/lib/solidus_dev_support/rake_tasks.rb#L41).

By the way, do we know what that's an issue now but it wasn't in the past? If that's possible, it would shed some light here! 🙂

2022-06-02 11:23 UTC, waiting-for-dev commented on Rakefile
> +require 'spree/frontend'
However, if I'm not missing something, this file is generated from a [template in solidus_dev_support](https://github.com/solidusio/solidus_dev_support/blob/master/lib/solidus_dev_support/templates/extension/Rakefile).

2022-06-21 10:07 UTC, gsmendoza commented
I'm closing this because this has been resolved in https://github.com/solidusio/solidus/pull/4411.

2022-06-21 10:07 UTC, closed without merging